from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
from PyQt5.QtWidgets import QMessageBox
from fpdf import FPDF

class Ui_Agentdet(object):
    def setupUi(self, Agentdet):
        Agentdet.setObjectName("Agentdet")
        Agentdet.resize(1368, 878)
        Agentdet.setMinimumSize(QtCore.QSize(1368, 878))
        Agentdet.setMaximumSize(QtCore.QSize(1368, 878))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        Agentdet.setFont(font)
        self.centralwidget = QtWidgets.QWidget(Agentdet)
        self.centralwidget.setObjectName("centralwidget")
        self.F1 = QtWidgets.QFrame(self.centralwidget)
        self.F1.setGeometry(QtCore.QRect(30, 20, 1368, 878))
        self.F1.setMinimumSize(QtCore.QSize(1368, 878))
        self.F1.setMaximumSize(QtCore.QSize(1368, 878))
        self.F1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.F1.setStyleSheet("background-color: rgb(188, 129, 200);")
        self.F1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.F1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.F1.setObjectName("F1")
        self.agentdetailstable = QtWidgets.QTableWidget(self.F1)
        self.agentdetailstable.setGeometry(QtCore.QRect(90, 160, 1131, 361))
        self.agentdetailstable.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.agentdetailstable.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.agentdetailstable.setObjectName("agentdetailstable")
        self.agentdetailstable.setColumnCount(10)
        self.agentdetailstable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.agentdetailstable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        item.setFont(font)
        self.agentdetailstable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.agentdetailstable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.agentdetailstable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.agentdetailstable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.agentdetailstable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.agentdetailstable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.agentdetailstable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.agentdetailstable.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.agentdetailstable.setHorizontalHeaderItem(9, item)
        self.label = QtWidgets.QLabel(self.F1)
        self.label.setGeometry(QtCore.QRect(600, 50, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pdfbut = QtWidgets.QPushButton(self.F1)
        self.pdfbut.setGeometry(QtCore.QRect(530, 620, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pdfbut.setFont(font)
        self.pdfbut.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pdfbut.setStyleSheet("background-color: rgb(87, 188, 255);\n"
"background-color: rgb(200, 200, 200);\n"
"border-radius:20px;")
        self.pdfbut.setObjectName("pdfbut")
        Agentdet.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Agentdet)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1368, 27))
        self.menubar.setObjectName("menubar")
        Agentdet.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Agentdet)
        self.statusbar.setObjectName("statusbar")
        Agentdet.setStatusBar(self.statusbar)

        self.showtable()
        self.pdfbut.clicked.connect(self.repPDF)

        self.retranslateUi(Agentdet)
        QtCore.QMetaObject.connectSlotsByName(Agentdet)

    def retranslateUi(self, Agentdet):
        _translate = QtCore.QCoreApplication.translate
        Agentdet.setWindowTitle(_translate("Agentdet", "AGENT DETAILS"))
        item = self.agentdetailstable.horizontalHeaderItem(0)
        item.setText(_translate("Agentdet", "AGENT_ID"))
        item = self.agentdetailstable.horizontalHeaderItem(1)
        item.setText(_translate("Agentdet", "AGENT NAME"))
        item = self.agentdetailstable.horizontalHeaderItem(2)
        item.setText(_translate("Agentdet", "EMAIL"))
        item = self.agentdetailstable.horizontalHeaderItem(3)
        item.setText(_translate("Agentdet", "PHONE NO"))
        item = self.agentdetailstable.horizontalHeaderItem(4)
        item.setText(_translate("Agentdet", "D.O.B"))
        item = self.agentdetailstable.horizontalHeaderItem(5)
        item.setText(_translate("Agentdet", "GENDER"))
        item = self.agentdetailstable.horizontalHeaderItem(6)
        item.setText(_translate("Agentdet", "ADDRESS"))
        item = self.agentdetailstable.horizontalHeaderItem(7)
        item.setText(_translate("Agentdet", "AADHAR NO"))
        item = self.agentdetailstable.horizontalHeaderItem(8)
        item.setText(_translate("Agentdet", "PAN NO"))
        item = self.agentdetailstable.horizontalHeaderItem(9)
        item.setText(_translate("Agentdet", "WORKEXPERIENCE"))
        self.label.setText(_translate("Agentdet", "AGENT DETAILS"))
        self.pdfbut.setText(_translate("Agentdet", "GENERATE PDF"))

    def showtable(self):
        con = sqlite3.connect("UMRS.db")
        cur = con.cursor()
        q = "select * from AgentReg"
        cur.execute(q)
        res= cur.fetchall()
        if res == []:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("Purchase not done yet")
            msg.setWindowTitle("Invalid")
            msg.show()
            msg.exec_()    
        else:
            self.agentdetailstable.setRowCount(0)
            for i in res:
                # print(i)
                rc = self.agentdetailstable.rowCount()
                self.agentdetailstable.insertRow(rc)
                self.agentdetailstable.setItem(rc,0,QtWidgets.QTableWidgetItem(str(i[0])))
                self.agentdetailstable.setItem(rc,1,QtWidgets.QTableWidgetItem(i[1]))
                self.agentdetailstable.setItem(rc,2,QtWidgets.QTableWidgetItem(i[2]))
                self.agentdetailstable.setItem(rc,3,QtWidgets.QTableWidgetItem(str(i[3])))
                self.agentdetailstable.setItem(rc,4,QtWidgets.QTableWidgetItem(str(i[4])))
                self.agentdetailstable.setItem(rc,5,QtWidgets.QTableWidgetItem(str(i[5])))
                self.agentdetailstable.setItem(rc,6,QtWidgets.QTableWidgetItem(i[6]))
                self.agentdetailstable.setItem(rc,7,QtWidgets.QTableWidgetItem(str(i[7])))
                self.agentdetailstable.setItem(rc,8,QtWidgets.QTableWidgetItem(i[8]))
                self.agentdetailstable.setItem(rc,9,QtWidgets.QTableWidgetItem(str(i[10])))

    def repPDF(self):
        spacing=4    
        con = sqlite3.connect("UMRS.db")
        cur = con.cursor()
        q = "select AID,AgentName,Email,PhoneNo,DOB,Gender,Address,AadharNo,PanNo,WorkExperience from AgentReg"
        cur.execute(q)
        res= cur.fetchall()
        # data = [('PYTHON/001', 'Pyhton', 'The ABC of Python', 'Souvik Karmakar', '2023-07-11', '2023-07-15', '2023-07-27', 'F101'), ('JAVA/002', 'Java', 'The XYZ of Java', 'Souvik Karmakar', '2023-07-25', '2023-08-08', '2023-07-27', 'NULL'), ('PYTHON/003', 'Pyhton', 'The ABC of Python', 'Souvik Karmakar', '2023-07-25', '2023-08-08', '2023-07-25', 'NULL'), ('JAVA/001','Java', 'The XYZ of Java', 'Souvik Karmakar', '2023-07-20', '2023-08-26', '2023-07-27', 'NULL'), ('JAVA/002', 'Java', 'The XYZ of Java', 'Souvik Karmakar', '2023-07-20', '2023-07-26', '2023-07-27', 'F103'), ('gf', 'Java', 'The XYZ of Java', 'Souvik Karmakar', '2023-07-25', '2023-08-08', 'NULL', 'NULL'), ('ghg', 'Pyhton', 'The ABC of Python', 'Souvik Karmakar', '2023-07-25', '2023-08-08', 'NULL', 'NULL'), ('abv', 'Java', 'The XYZ of Java', 'Souvik Karmakar', '2023-07-26', '2023-08-08', 'NULL', 'NULL')]
        data = [[str(i) for i in j] for j in res]
        # data.insert(0,('A','b','c','d','e','f','g','h'))
        data.insert(0,('AID','AgentName','Email','PhoneNo','DOB','Gender','Address','AadharNo','PanNo','WorkExperience'))
        pdf = FPDF('L','mm','A4')
        pdf.set_font('helvetica','B',9)
        pdf.add_page()

        col_width = pdf.w / 10.5
        row_height = pdf.font_size
        for row in data:
            for item in row:
                pdf.cell(col_width, row_height*spacing, txt=item, border=2)
            pdf.ln(row_height*spacing)
            
        pdf.output('Agent Details.pdf')


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Agentdet = QtWidgets.QMainWindow()
    ui = Ui_Agentdet()
    ui.setupUi(Agentdet)
    Agentdet.show()
    sys.exit(app.exec_())
