from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
from datetime import datetime
from PyQt5.QtWidgets import QMessageBox
from addbankname import *


class Ui_Registration_page(object):
    def setupUi(self, Registration_page):
        Registration_page.setObjectName("Registration_page")
        Registration_page.resize(1368, 878)
        Registration_page.setMinimumSize(QtCore.QSize(1368, 878))
        Registration_page.setMaximumSize(QtCore.QSize(1368, 878))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        Registration_page.setFont(font)
        Registration_page.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.centralwidget = QtWidgets.QWidget(Registration_page)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(570, 10, 411, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(211, 211, 211);")
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(540, 100, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(550, 150, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(550, 360, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(550, 310, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.fnametext = QtWidgets.QLineEdit(self.centralwidget)
        self.fnametext.setGeometry(QtCore.QRect(660, 110, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.fnametext.setFont(font)
        self.fnametext.setText("")
        self.fnametext.setObjectName("fnametext")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(550, 210, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(550, 260, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.male = QtWidgets.QRadioButton(self.centralwidget)
        self.male.setGeometry(QtCore.QRect(670, 270, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.male.setFont(font)
        self.male.setObjectName("male")
        self.female = QtWidgets.QRadioButton(self.centralwidget)
        self.female.setGeometry(QtCore.QRect(780, 270, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.female.setFont(font)
        self.female.setObjectName("female")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(550, 410, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(550, 460, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.regbut = QtWidgets.QPushButton(self.centralwidget)
        self.regbut.setGeometry(QtCore.QRect(680, 650, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.regbut.setFont(font)
        self.regbut.setStyleSheet("background-color: rgb(211, 211, 211);")
        self.regbut.setObjectName("regbut")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 190, 120, 80))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(50, 20, 271, 821))
        self.frame_2.setStyleSheet("background-color: rgb(168, 151, 255);\n"
"border-radius:10px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.addressstext = QtWidgets.QLineEdit(self.centralwidget)
        self.addressstext.setGeometry(QtCore.QRect(670, 320, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.addressstext.setFont(font)
        self.addressstext.setText("")
        self.addressstext.setObjectName("addressstext")
        self.phonetext = QtWidgets.QLineEdit(self.centralwidget)
        self.phonetext.setGeometry(QtCore.QRect(670, 370, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.phonetext.setFont(font)
        self.phonetext.setText("")
        self.phonetext.setObjectName("phonetext")
        self.pantext = QtWidgets.QLineEdit(self.centralwidget)
        self.pantext.setGeometry(QtCore.QRect(670, 470, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pantext.setFont(font)
        self.pantext.setText("")
        self.pantext.setObjectName("pantext")
        self.aadhartext = QtWidgets.QLineEdit(self.centralwidget)
        self.aadhartext.setGeometry(QtCore.QRect(670, 420, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.aadhartext.setFont(font)
        self.aadhartext.setText("")
        self.aadhartext.setObjectName("aadhartext")
        self.emailtext = QtWidgets.QLineEdit(self.centralwidget)
        self.emailtext.setGeometry(QtCore.QRect(660, 160, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.emailtext.setFont(font)
        self.emailtext.setText("")
        self.emailtext.setObjectName("emailtext")
        self.otherbox = QtWidgets.QRadioButton(self.centralwidget)
        self.otherbox.setGeometry(QtCore.QRect(900, 280, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.otherbox.setFont(font)
        self.otherbox.setObjectName("otherbox")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(550, 570, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(750, 570, 261, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(550, 510, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.bankcom = QtWidgets.QComboBox(self.centralwidget)
        self.bankcom.setGeometry(QtCore.QRect(670, 520, 261, 31))
        self.bankcom.setObjectName("bankcom")
        self.otherbut = QtWidgets.QPushButton(self.centralwidget)
        self.otherbut.setGeometry(QtCore.QRect(950, 520, 151, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.otherbut.setFont(font)
        self.otherbut.setStyleSheet("background-color: rgb(198, 198, 198);")
        self.otherbut.setObjectName("otherbut")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(660, 220, 211, 41))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        Registration_page.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Registration_page)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1368, 27))
        self.menubar.setObjectName("menubar")
        Registration_page.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Registration_page)
        self.statusbar.setObjectName("statusbar")
        Registration_page.setStatusBar(self.statusbar)

        self.regbut.clicked.connect(self.reg)
        self.otherbut.clicked.connect(self.otherbank)
        self.showbn()

        self.retranslateUi(Registration_page)
        QtCore.QMetaObject.connectSlotsByName(Registration_page)

    def retranslateUi(self, Registration_page):
        _translate = QtCore.QCoreApplication.translate
        Registration_page.setWindowTitle(_translate("Registration_page", "Agent Registration page"))
        self.label.setText(_translate("Registration_page", " AGENT Registration Page"))
        self.label_4.setText(_translate("Registration_page", " Name:"))
        self.label_7.setText(_translate("Registration_page", "Email :"))
        self.label_8.setText(_translate("Registration_page", "Phone No. :"))
        self.label_9.setText(_translate("Registration_page", "Address: "))
        self.label_10.setText(_translate("Registration_page", "D.O.B:"))
        self.label_11.setText(_translate("Registration_page", "Gender:"))
        self.male.setText(_translate("Registration_page", "Male"))
        self.female.setText(_translate("Registration_page", "Female"))
        self.label_12.setText(_translate("Registration_page", "Aadhar No.: "))
        self.label_13.setText(_translate("Registration_page", "Pan No."))
        self.regbut.setText(_translate("Registration_page", "Register"))
        self.otherbox.setText(_translate("Registration_page", "Others"))
        self.label_2.setText(_translate("Registration_page", "WORK EXPERIENCE:"))
        self.comboBox.setItemText(0, _translate("Registration_page", "0-1 year"))
        self.comboBox.setItemText(1, _translate("Registration_page", "1-2 year"))
        self.comboBox.setItemText(2, _translate("Registration_page", "2-5 year"))
        self.comboBox.setItemText(3, _translate("Registration_page", "5-10 year"))
        self.label_14.setText(_translate("Registration_page", "Bank:"))
        self.otherbut.setText(_translate("Registration_page", "Other Bnak"))

    def showbn(self):
        bn = self.bankcom.currentText()
        con = sqlite3.connect("UMRS.db")
        cur = con.cursor()
        q1 = "select BankName from Bank_Name"
        cur.execute(q1,(bn))
        c = cur.fetchall()
        for i in c:
            self.bankcom.addItem(i[0])
        con.commit()

    def otherbank(self):
        self.Add_Bank_Name = QtWidgets.QMainWindow()
        self.ui = Ui_Add_Bank_Name()
        self.ui.setupUi(self.Add_Bank_Name)
        self.Add_Bank_Name.show()

    def reg(self):
        name= self.fnametext.text()
        email = self.emailtext.text()
        aadhar = self.aadhartext.text()
        pan = self.pantext.text()
        mob = str(self.phonetext.text())

        add = self.addressstext.text()
        dob = self.dateEdit.text()
        bn=self.bankcom.currentText()
        wex = self.comboBox.currentText()
        if self.male.isChecked():
            gen = "Male"
        elif self.female.isChecked():
            gen = "Female"
        elif self.otherbox.isChecked():
            gen = "Others"
        con = sqlite3.connect("UMRS.db")
        cur = con.cursor()
        cur1 = con.cursor()
        q =  "Select aid from AgentReg order by AID desc limit 1"
        cur1.execute(q)
        res = cur1.fetchall()
        aid = res[0][0] + 1
        if name=="" or email== "" or aadhar== "" or pan== "" or mob== "" or add== "" or dob== "" or wex== "":
            if name=="": 
                    msg = QMessageBox()
                    msg.setIcon(QMessageBox.Critical)
                    msg.setText("Name field cann't be empty")
                    msg.setWindowTitle("Warning")
                    msg.show()
                    msg.exec_()
            elif email=="": 
                    msg = QMessageBox()
                    msg.setIcon(QMessageBox.Critical)
                    msg.setText("Email field cann't be empty")
                    msg.setWindowTitle("Warning")
                    msg.show()
                    msg.exec_()

            elif aadhar=="": 
                    msg = QMessageBox()
                    msg.setIcon(QMessageBox.Critical)
                    msg.setText("Aadhar field cann't be empty")
                    msg.setWindowTitle("Warning")
                    msg.show()
                    msg.exec_()  

            elif pan=="": 
                    msg = QMessageBox()
                    msg.setIcon(QMessageBox.Critical)
                    msg.setText("Pan field cann't be empty")
                    msg.setWindowTitle("Warning")
                    msg.show()
                    msg.exec_()

            elif mob=="": 
                    msg = QMessageBox()
                    msg.setIcon(QMessageBox.Critical)
                    msg.setText("Mobile field cann't be empty")
                    msg.setWindowTitle("Warning")
                    msg.show()
                    msg.exec_()

            elif mob!="" and len(mob) != 10:
                    msg = QMessageBox()
                    msg.setIcon(QMessageBox.Critical)
                    msg.setText("Moblie number should be 10 digit")
                    msg.setWindowTitle("Warning")
                    msg.show()
                    msg.exec_()


            elif add=="": 
                    msg = QMessageBox()
                    msg.setIcon(QMessageBox.Critical)
                    msg.setText("Address field cann't be empty")
                    msg.setWindowTitle("Warning")
                    msg.show()
                    msg.exec_()

            elif dob=="": 
                    msg = QMessageBox()
                    msg.setIcon(QMessageBox.Critical)
                    msg.setText("D.O.B field cann't be empty")
                    msg.setWindowTitle("Warning")
                    msg.show()
                    msg.exec_()  

            elif wex=="": 
                    msg = QMessageBox()
                    msg.setIcon(QMessageBox.Critical)
                    msg.setText("Work Experience field cann't be empty")
                    msg.setWindowTitle("Warning")
                    msg.show()
                    msg.exec_()

            else:
                    msg = QMessageBox()
                    msg.setIcon(QMessageBox.Critical)
                    msg.setText("Fill up all empty fields")
                    msg.setWindowTitle("Warning")
                    msg.show()
                    msg.exec_()

        else:
                q= "insert into AgentReg values(?,?,?,?,?,?,?,?,?,?,?)"
                cur.execute(q,(aid,name,email,mob,dob,gen,add,aadhar,pan,bn,wex))
                con.commit()
                # print(uid,name,email,aadhar,pan,mob,add,dob,gen,bn,accno,ifsc)


                msg = QMessageBox()
                msg.setIcon(QMessageBox.Information)
                msg.setText("Registerd")
                msg.setWindowTitle("Add successful")
                msg.show()
                msg.exec_()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Registration_page = QtWidgets.QMainWindow()
    ui = Ui_Registration_page()
    ui.setupUi(Registration_page)
    Registration_page.show()
    sys.exit(app.exec_())
