from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
from PyQt5.QtWidgets import QMessageBox
from fpdf import FPDF


class Ui_CUSTOMERDETAILS(object):
    def setupUi(self, CUSTOMERDETAILS):
        CUSTOMERDETAILS.setObjectName("CUSTOMERDETAILS")
        CUSTOMERDETAILS.resize(1368, 878)
        CUSTOMERDETAILS.setMinimumSize(QtCore.QSize(1368, 878))
        CUSTOMERDETAILS.setMaximumSize(QtCore.QSize(1368, 878))
        self.centralwidget = QtWidgets.QWidget(CUSTOMERDETAILS)
        self.centralwidget.setObjectName("centralwidget")
        self.F1 = QtWidgets.QFrame(self.centralwidget)
        self.F1.setGeometry(QtCore.QRect(20, 30, 1368, 878))
        self.F1.setMinimumSize(QtCore.QSize(1368, 878))
        self.F1.setMaximumSize(QtCore.QSize(1368, 878))
        self.F1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.F1.setStyleSheet("background-color: rgb(188, 129, 200);")
        self.F1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.F1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.F1.setObjectName("F1")
        self.customerdetails = QtWidgets.QTableWidget(self.F1)
        self.customerdetails.setGeometry(QtCore.QRect(70, 160, 1151, 361))
        self.customerdetails.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.customerdetails.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.customerdetails.setObjectName("customerdetails")
        self.customerdetails.setColumnCount(12)
        self.customerdetails.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.customerdetails.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        item.setFont(font)
        self.customerdetails.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.customerdetails.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.customerdetails.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.customerdetails.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.customerdetails.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.customerdetails.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.customerdetails.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.customerdetails.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.customerdetails.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.customerdetails.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.customerdetails.setHorizontalHeaderItem(11, item)
        self.label = QtWidgets.QLabel(self.F1)
        self.label.setGeometry(QtCore.QRect(600, 50, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pdfbut = QtWidgets.QPushButton(self.F1)
        self.pdfbut.setGeometry(QtCore.QRect(530, 620, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pdfbut.setFont(font)
        self.pdfbut.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pdfbut.setStyleSheet("background-color: rgb(87, 188, 255);\n"
"background-color: rgb(200, 200, 200);\n"
"border-radius:20px;")
        self.pdfbut.setObjectName("pdfbut")
        CUSTOMERDETAILS.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CUSTOMERDETAILS)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1368, 27))
        self.menubar.setObjectName("menubar")
        CUSTOMERDETAILS.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CUSTOMERDETAILS)
        self.statusbar.setObjectName("statusbar")
        CUSTOMERDETAILS.setStatusBar(self.statusbar)

        self.pdfbut.clicked.connect(self.repPDF)
        self.showtable()

        self.retranslateUi(CUSTOMERDETAILS)
        QtCore.QMetaObject.connectSlotsByName(CUSTOMERDETAILS)

    def retranslateUi(self, CUSTOMERDETAILS):
        _translate = QtCore.QCoreApplication.translate
        CUSTOMERDETAILS.setWindowTitle(_translate("CUSTOMERDETAILS", "Customer Details"))
        item = self.customerdetails.horizontalHeaderItem(0)
        item.setText(_translate("CUSTOMERDETAILS", "CUSTOMER_ID"))
        item = self.customerdetails.horizontalHeaderItem(1)
        item.setText(_translate("CUSTOMERDETAILS", "CUSTOMER NAME"))
        item = self.customerdetails.horizontalHeaderItem(2)
        item.setText(_translate("CUSTOMERDETAILS", "EMAIL"))
        item = self.customerdetails.horizontalHeaderItem(3)
        item.setText(_translate("CUSTOMERDETAILS", "AADHAR NO"))
        item = self.customerdetails.horizontalHeaderItem(4)
        item.setText(_translate("CUSTOMERDETAILS", "PAN NO"))
        item = self.customerdetails.horizontalHeaderItem(5)
        item.setText(_translate("CUSTOMERDETAILS", "PHONE NO"))
        item = self.customerdetails.horizontalHeaderItem(6)
        item.setText(_translate("CUSTOMERDETAILS", "ADDRESS"))
        item = self.customerdetails.horizontalHeaderItem(7)
        item.setText(_translate("CUSTOMERDETAILS", "D.O.B"))
        item = self.customerdetails.horizontalHeaderItem(8)
        item.setText(_translate("CUSTOMERDETAILS", "GENDER"))
        item = self.customerdetails.horizontalHeaderItem(9)
        item.setText(_translate("CUSTOMERDETAILS", "BankName"))
        item = self.customerdetails.horizontalHeaderItem(10)
        item.setText(_translate("CUSTOMERDETAILS", "ACNo"))
        item = self.customerdetails.horizontalHeaderItem(11)
        item.setText(_translate("CUSTOMERDETAILS", "IFSCcode"))
        self.label.setText(_translate("CUSTOMERDETAILS", "CUSTOMER DETAILS"))
        self.pdfbut.setText(_translate("CUSTOMERDETAILS", "GENERATE PDF"))

    def showtable(self):
        con = sqlite3.connect("UMRS.db")
        cur = con.cursor()
        q = "select * from CoustomerReg"
        cur.execute(q)
        res= cur.fetchall()
        if res == []:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("Purchase not done yet")
            msg.setWindowTitle("Invalid")
            msg.show()
            msg.exec_()    
        else:
            self.customerdetails.setRowCount(0)
            for i in res:
                # print(i)
                rc = self.customerdetails.rowCount()
                self.customerdetails.insertRow(rc)
                self.customerdetails.setItem(rc,0,QtWidgets.QTableWidgetItem(str(i[0])))
                self.customerdetails.setItem(rc,1,QtWidgets.QTableWidgetItem(i[1]))
                self.customerdetails.setItem(rc,2,QtWidgets.QTableWidgetItem(i[2]))
                self.customerdetails.setItem(rc,3,QtWidgets.QTableWidgetItem(str(i[3])))
                self.customerdetails.setItem(rc,4,QtWidgets.QTableWidgetItem(str(i[4])))
                self.customerdetails.setItem(rc,5,QtWidgets.QTableWidgetItem(str(i[5])))
                self.customerdetails.setItem(rc,6,QtWidgets.QTableWidgetItem(i[6]))
                self.customerdetails.setItem(rc,7,QtWidgets.QTableWidgetItem(str(i[7])))
                self.customerdetails.setItem(rc,8,QtWidgets.QTableWidgetItem(i[8]))
                self.customerdetails.setItem(rc,9,QtWidgets.QTableWidgetItem(str(i[9])))
                self.customerdetails.setItem(rc,10,QtWidgets.QTableWidgetItem(str(i[10])))
                self.customerdetails.setItem(rc,11,QtWidgets.QTableWidgetItem(str(i[11])))


    def repPDF(self):
        spacing=4    
        con = sqlite3.connect("UMRS.db")
        cur = con.cursor()
        q = "select UID,Name,Email,AadharNo,PanNo,PhoneNo,Address,DOB,Gender,BankName,ACNo,IFSCcode from CoustomerReg"
        cur.execute(q)
        res= cur.fetchall()
        # data = [('PYTHON/001', 'Pyhton', 'The ABC of Python', 'Souvik Karmakar', '2023-07-11', '2023-07-15', '2023-07-27', 'F101'), ('JAVA/002', 'Java', 'The XYZ of Java', 'Souvik Karmakar', '2023-07-25', '2023-08-08', '2023-07-27', 'NULL'), ('PYTHON/003', 'Pyhton', 'The ABC of Python', 'Souvik Karmakar', '2023-07-25', '2023-08-08', '2023-07-25', 'NULL'), ('JAVA/001','Java', 'The XYZ of Java', 'Souvik Karmakar', '2023-07-20', '2023-08-26', '2023-07-27', 'NULL'), ('JAVA/002', 'Java', 'The XYZ of Java', 'Souvik Karmakar', '2023-07-20', '2023-07-26', '2023-07-27', 'F103'), ('gf', 'Java', 'The XYZ of Java', 'Souvik Karmakar', '2023-07-25', '2023-08-08', 'NULL', 'NULL'), ('ghg', 'Pyhton', 'The ABC of Python', 'Souvik Karmakar', '2023-07-25', '2023-08-08', 'NULL', 'NULL'), ('abv', 'Java', 'The XYZ of Java', 'Souvik Karmakar', '2023-07-26', '2023-08-08', 'NULL', 'NULL')]
        data = [[str(i) for i in j] for j in res]
        # data.insert(0,('A','b','c','d','e','f','g','h'))
        data.insert(0,('UID','Name','Email','AadharNo','PanNo','PhoneNo','Address','DOB','Gender','BankName','ACNo','IFSCcode'))
        pdf = FPDF('L','mm','A4')
        pdf.set_font('helvetica','B',7)
        pdf.add_page()

        col_width = pdf.w / 12.5
        row_height = pdf.font_size
        for row in data:
            for item in row:
                pdf.cell(col_width, row_height*spacing, txt=item, border=2)
            pdf.ln(row_height*spacing)
            
        pdf.output('Customer details.pdf')


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CUSTOMERDETAILS = QtWidgets.QMainWindow()
    ui = Ui_CUSTOMERDETAILS()
    ui.setupUi(CUSTOMERDETAILS)
    CUSTOMERDETAILS.show()
    sys.exit(app.exec_())
