from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
from datetime import datetime
from datetime import date
from PyQt5.QtWidgets import QMessageBox
from addbankname import *
import re
# from PyQt5 import QtCore , QtGui
# from PyQt5.QtGui import *
# from PyQt5.QtCore import *
# import sys
# import Qdate

class Ui_cReg(object):
    def setupUi(self, cReg):
        cReg.setObjectName("cReg")
        cReg.resize(1368, 878)
        cReg.setMinimumSize(QtCore.QSize(1368, 878))
        cReg.setMaximumSize(QtCore.QSize(1368, 878))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        cReg.setFont(font)
        self.centralwidget = QtWidgets.QWidget(cReg)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(540, 10, 411, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(530, 80, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(540, 130, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(540, 280, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(540, 340, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.fnametext = QtWidgets.QLineEdit(self.centralwidget)
        self.fnametext.setGeometry(QtCore.QRect(660, 90, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.fnametext.setFont(font)
        self.fnametext.setText("")
        self.fnametext.setObjectName("fnametext")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(540, 410, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(540, 470, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.male = QtWidgets.QRadioButton(self.centralwidget)
        self.male.setGeometry(QtCore.QRect(670, 480, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.male.setFont(font)
        self.male.setCheckable(True)
        self.male.setChecked(False)
        self.male.setObjectName("male")
        self.female = QtWidgets.QRadioButton(self.centralwidget)
        self.female.setGeometry(QtCore.QRect(780, 480, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.female.setFont(font)
        self.female.setObjectName("female")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(540, 180, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(540, 230, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.regbut = QtWidgets.QPushButton(self.centralwidget)
        self.regbut.setGeometry(QtCore.QRect(710, 740, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.regbut.setFont(font)
        self.regbut.setStyleSheet("background-color: rgb(252,198, 255);\n"
"background-color: rgb(193, 193, 193);")
        self.regbut.setObjectName("regbut")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 190, 120, 80))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(50, 20, 271, 781))
        self.frame_2.setStyleSheet("background-color: rgb(199, 162, 255);\n"
"border-radius:20px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(540, 550, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(670, 540, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(540, 670, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(540, 610, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.ifsctext = QtWidgets.QLineEdit(self.centralwidget)
        self.ifsctext.setGeometry(QtCore.QRect(670, 670, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ifsctext.setFont(font)
        self.ifsctext.setText("")
        self.ifsctext.setObjectName("ifsctext")
        self.acctext = QtWidgets.QLineEdit(self.centralwidget)
        self.acctext.setGeometry(QtCore.QRect(670, 610, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.acctext.setFont(font)
        self.acctext.setText("")
        self.acctext.setObjectName("acctext")
        self.fnametext_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.fnametext_4.setGeometry(QtCore.QRect(660, 350, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.fnametext_4.setFont(font)
        self.fnametext_4.setText("")
        self.fnametext_4.setObjectName("fnametext_4")
        self.fnametext_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.fnametext_5.setGeometry(QtCore.QRect(660, 290, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.fnametext_5.setFont(font)
        self.fnametext_5.setText("")
        self.fnametext_5.setObjectName("fnametext_5")
        self.pantext = QtWidgets.QLineEdit(self.centralwidget)
        self.pantext.setGeometry(QtCore.QRect(660, 240, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pantext.setFont(font)
        self.pantext.setText("")
        self.pantext.setObjectName("pantext")
        self.aadhartext = QtWidgets.QLineEdit(self.centralwidget)
        self.aadhartext.setGeometry(QtCore.QRect(660, 190, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.aadhartext.setFont(font)
        self.aadhartext.setText("")
        self.aadhartext.setObjectName("aadhartext")
        self.emailtext = QtWidgets.QLineEdit(self.centralwidget)
        self.emailtext.setGeometry(QtCore.QRect(660, 140, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.emailtext.setFont(font)
        self.emailtext.setText("")
        self.emailtext.setObjectName("emailtext")
        self.other = QtWidgets.QRadioButton(self.centralwidget)
        self.other.setGeometry(QtCore.QRect(910, 480, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.other.setFont(font)
        self.other.setObjectName("other")
        self.otherbut = QtWidgets.QPushButton(self.centralwidget)
        self.otherbut.setGeometry(QtCore.QRect(950, 540, 151, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.otherbut.setFont(font)
        self.otherbut.setStyleSheet("background-color: rgb(198, 198, 198);")
        self.otherbut.setObjectName("otherbut")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(660, 420, 211, 41))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        cReg.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(cReg)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1368, 27))
        self.menubar.setObjectName("menubar")
        cReg.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(cReg)
        self.statusbar.setObjectName("statusbar")
        cReg.setStatusBar(self.statusbar)

        self.regbut.clicked.connect(self.reg)
        self.otherbut.clicked.connect(self.otherbank)
        self.bankname()

        self.retranslateUi(cReg)
        QtCore.QMetaObject.connectSlotsByName(cReg)

    def retranslateUi(self, cReg):
        _translate = QtCore.QCoreApplication.translate
        cReg.setWindowTitle(_translate("cReg", "Customer Registration page"))
        self.label.setText(_translate("cReg", "Customer Registration Form"))
        self.label_4.setText(_translate("cReg", " Name:"))
        self.label_7.setText(_translate("cReg", "Email :"))
        self.label_8.setText(_translate("cReg", "Phone No. :"))
        self.label_9.setText(_translate("cReg", "Address: "))
        self.label_10.setText(_translate("cReg", "D.O.B:"))
        self.label_11.setText(_translate("cReg", "Gender:"))
        self.male.setText(_translate("cReg", "Male"))
        self.female.setText(_translate("cReg", "Female"))
        self.label_12.setText(_translate("cReg", "Aadhar No.: "))
        self.label_13.setText(_translate("cReg", "Pan No."))
        self.regbut.setText(_translate("cReg", "Register"))
        self.label_2.setText(_translate("cReg", "Bank Name:"))
        self.label_3.setText(_translate("cReg", "IFSC NO:"))
        self.label_5.setText(_translate("cReg", "ACCOUNT NO:"))
        self.other.setText(_translate("cReg", "Others"))
        self.otherbut.setText(_translate("cReg", "Other Bnak"))


    def reg(self):
        name= self.fnametext.text()
        email = self.emailtext.text()
        aadhar = self.aadhartext.text()
        pan = self.pantext.text()
        mob = str(self.fnametext_5.text())

        add = self.fnametext_4.text()
        dob = (self.dateEdit.text())
        bn = self.comboBox.currentText()
        accno = self.acctext.text()
        ifsc = self.ifsctext.text()
        # ifscc=re.compile(r"^[A-Z]{4}0\d{6}$")
        # regex=("[A-Z]{5}[0-9]{4}[A-Z]{1}")
        # pann=re.compile(regex)
        if self.male.isChecked():
            gen = "Male"
        elif self.female.isChecked():
            gen = "Female"
        elif self.other.isChecked():
            gen = "Others"
        
        con = sqlite3.connect("UMRS.db")
        cur = con.cursor()
        cur1 = con.cursor()
        q =  "Select uid from CoustomerReg order by UID desc limit 1"
        cur1.execute(q)
        res = cur1.fetchall()
        uid = res[0][0] + 1
        if name=="" or email== "" or aadhar== "" or pan== "" or mob== "" or add== "" or dob== "" or bn== "" or accno== "" or ifsc== "":
            if name=="": 
                    msg = QMessageBox()
                    msg.setIcon(QMessageBox.Critical)
                    msg.setText("Name field cann't be empty")
                    msg.setWindowTitle("Warning")
                    msg.show()
                    msg.exec_()
            elif email=="": 
                    msg = QMessageBox()
                    msg.setIcon(QMessageBox.Critical)
                    msg.setText("Email field cann't be empty")
                    msg.setWindowTitle("Warning")
                    msg.show()
                    msg.exec_()

            elif aadhar=="": 
                    msg = QMessageBox()
                    msg.setIcon(QMessageBox.Critical)
                    msg.setText("Aadhar field cann't be empty")
                    msg.setWindowTitle("Warning")
                    msg.show()
                    msg.exec_() 

            elif aadhar!="" and len(aadhar)!=12: 
                    msg = QMessageBox()
                    msg.setIcon(QMessageBox.Critical)
                    msg.setText("Aadhar number should be 12 digits.")
                    msg.setWindowTitle("Warning")
                    msg.show()
                    msg.exec_()  

            elif pan=="": 
                    msg = QMessageBox()
                    msg.setIcon(QMessageBox.Critical)
                    msg.setText("Pan field cann't be empty")
                    msg.setWindowTitle("Warning")
                    msg.show()
                    msg.exec_()

        #     elif (re.search(pann,pan) and len(pan)!=10): 
        #             msg = QMessageBox()
        #             msg.setIcon(QMessageBox.Critical)
        #             msg.setText("Again enter Pan number")
        #             msg.setWindowTitle("Warning")
        #             msg.show()
        #             msg.exec_()

        #     elif not ifsc.match(ifscc): 
        #             msg = QMessageBox()
        #             msg.setIcon(QMessageBox.Critical)
        #             msg.setText("Wrong IFSC code please enter again.")
        #             msg.setWindowTitle("Warning")
        #             msg.show()
        #             msg.exec_()

            elif mob=="": 
                    msg = QMessageBox()
                    msg.setIcon(QMessageBox.Critical)
                    msg.setText("Mobile field cann't be empty")
                    msg.setWindowTitle("Warning")
                    msg.show()
                    msg.exec_()

            elif mob.isnumeric() == False:
                        msg = QMessageBox()
                        msg.setIcon(QMessageBox.Critical)
                        msg.setText("Mobile number should be numeric")
                        msg.setWindowTitle("Warning")
                        msg.show()
                        msg.exec_()

            elif mob!="" and len(mob) != 10:
                    msg = QMessageBox()
                    msg.setIcon(QMessageBox.Critical)
                    msg.setText("Moblie number should be 10 digit")
                    msg.setWindowTitle("Warning")
                    msg.show()
                    msg.exec_()


            elif add=="": 
                    msg = QMessageBox()
                    msg.setIcon(QMessageBox.Critical)
                    msg.setText("Address field cann't be empty")
                    msg.setWindowTitle("Warning")
                    msg.show()
                    msg.exec_()

            elif dob=="": 
                    msg = QMessageBox()
                    msg.setIcon(QMessageBox.Critical)
                    msg.setText("D.O.B field cann't be empty")
                    msg.setWindowTitle("Warning")
                    msg.show()
                    msg.exec_()  

            elif bn=="": 
                    msg = QMessageBox()
                    msg.setIcon(QMessageBox.Critical)
                    msg.setText("Bank Name field cann't be empty")
                    msg.setWindowTitle("Warning")
                    msg.show()
                    msg.exec_()

            elif accno=="": 
                    msg = QMessageBox()
                    msg.setIcon(QMessageBox.Critical)
                    msg.setText("Account Name field cann't be empty")
                    msg.setWindowTitle("Warning")
                    msg.show()
                    msg.exec_()

            elif ifsc=="": 
                    msg = QMessageBox()
                    msg.setIcon(QMessageBox.Critical)
                    msg.setText("IFSC Code field cann't be empty")
                    msg.setWindowTitle("Warning")
                    msg.show()
                    msg.exec_()

        else:
                q= "insert into CoustomerReg values(?,?,?,?,?,?,?,?,?,?,?,?)"
                cur.execute(q,(uid,name,email,aadhar,pan,mob,add,dob,gen,bn,accno,ifsc))
                con.commit()
                # print(uid,name,email,aadhar,pan,mob,add,dob,gen,bn,accno,ifsc)
                # print(dob)

                msg = QMessageBox()
                msg.setIcon(QMessageBox.Information)
                msg.setText("Registerd")
                msg.setWindowTitle("Add successful")
                msg.show()
                msg.exec_()

    def otherbank(self):
        self.Add_Bank_Name = QtWidgets.QMainWindow()
        self.ui = Ui_Add_Bank_Name()
        self.ui.setupUi(self.Add_Bank_Name)
        self.Add_Bank_Name.show()

    def bankname(self):
        bn = self.comboBox.currentText()
        con = sqlite3.connect("UMRS.db")
        cur = con.cursor()
        q1 = "select BankName from Bank_Name"
        cur.execute(q1,(bn))
        c = cur.fetchall()
        for i in c:
            self.comboBox.addItem(i[0])


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    cReg = QtWidgets.QMainWindow()
    ui = Ui_cReg()
    ui.setupUi(cReg)
    cReg.show()
    sys.exit(app.exec_())
