from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
from PyQt5.QtWidgets import QMessageBox


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1368, 878)
        MainWindow.setMinimumSize(QtCore.QSize(1368, 878))
        MainWindow.setMaximumSize(QtCore.QSize(1368, 878))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1551, 921))
        self.frame.setStyleSheet("\n"
"border-radius:20px")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 231, 841))
        self.frame_2.setStyleSheet("background-color: rgb(228, 120, 255);\n"
"border-radius:20px;\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.t1 = QtWidgets.QTableWidget(self.frame)
        self.t1.setGeometry(QtCore.QRect(260, 160, 1081, 351))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.t1.setFont(font)
        self.t1.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.t1.setStyleSheet("padding-left:3px;\n"
"border-color: rgb(0, 85, 255);\n"
"borde-radius:20px;\n"
"\n"
"")
        self.t1.setObjectName("t1")
        self.t1.setColumnCount(14)
        self.t1.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.t1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.t1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.t1.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.t1.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.t1.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.t1.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.t1.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.t1.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.t1.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.t1.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.t1.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.t1.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.t1.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.t1.setHorizontalHeaderItem(13, item)
        self.pb1 = QtWidgets.QPushButton(self.frame)
        self.pb1.setGeometry(QtCore.QRect(610, 580, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pb1.setFont(font)
        self.pb1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb1.setStyleSheet("background-color: rgb(194, 194, 194);")
        self.pb1.setAutoRepeat(False)
        self.pb1.setFlat(False)
        self.pb1.setObjectName("pb1")
        self.pb2 = QtWidgets.QPushButton(self.frame)
        self.pb2.setGeometry(QtCore.QRect(830, 580, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pb2.setFont(font)
        self.pb2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb2.setStyleSheet("background-color: rgb(179, 179, 179);\n"
"\n"
"\n"
"\n"
"")
        self.pb2.setObjectName("pb2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(630, 20, 241, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1368, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.showRequest()
        self.pb1.clicked.connect(self.allow)
        self.pb2.clicked.connect(self.deny)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Loan Request Page"))
        item = self.t1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "LID"))
        item = self.t1.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "NAME"))
        item = self.t1.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "EMAIL"))
        item = self.t1.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "PHONE NO"))
        item = self.t1.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "ADDRESS"))
        item = self.t1.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "AADHAAR NO"))
        item = self.t1.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "PAN NO"))
        item = self.t1.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "BANK NAME"))
        item = self.t1.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "ACNO"))
        item = self.t1.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "IFSC CODE"))
        item = self.t1.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "LOAN AMOUNT"))
        item = self.t1.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "LOAN TYPE"))
        item = self.t1.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "REQUEST DATE"))
        item = self.t1.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "TIME"))
        self.pb1.setText(_translate("MainWindow", "ALLOW"))
        self.pb2.setText(_translate("MainWindow", "DENY"))
        self.label.setText(_translate("MainWindow", "Request Page"))

    def showRequest(self):
        con = sqlite3.connect("UMRS.db")
        cur = con.cursor()
        q = "select LID,Name,Email,PhoneNo,Address,AadharNo,PAN_No,Bankname,AC_No,IFSCCode,LoanAmount,LoanType,RequestDate,time from Loan_Request"
        cur.execute(q)
        res = cur.fetchall()
        self.t1.setRowCount(0)
        for i in res:
            # print(i)
            rc = self.t1.rowCount()
            self.t1.insertRow(rc)
            self.t1.setItem(rc,0,QtWidgets.QTableWidgetItem(str(i[0])))
            self.t1.setItem(rc,1,QtWidgets.QTableWidgetItem(i[1]))
            self.t1.setItem(rc,2,QtWidgets.QTableWidgetItem(i[2]))
            self.t1.setItem(rc,3,QtWidgets.QTableWidgetItem(i[3]))
            self.t1.setItem(rc,4,QtWidgets.QTableWidgetItem(str(i[4])))
            self.t1.setItem(rc,5,QtWidgets.QTableWidgetItem(str(i[5])))
            self.t1.setItem(rc,6,QtWidgets.QTableWidgetItem(str(i[6])))
            self.t1.setItem(rc,7,QtWidgets.QTableWidgetItem(str(i[7])))
            self.t1.setItem(rc,8,QtWidgets.QTableWidgetItem(str(i[8])))
            self.t1.setItem(rc,9,QtWidgets.QTableWidgetItem(str(i[9])))
            self.t1.setItem(rc,10,QtWidgets.QTableWidgetItem(str(i[10])))
            self.t1.setItem(rc,11,QtWidgets.QTableWidgetItem(str(i[11])))
            self.t1.setItem(rc,12,QtWidgets.QTableWidgetItem(str(i[12])))
            self.t1.setItem(rc,13,QtWidgets.QTableWidgetItem(str(i[13])))
        con.commit()

    def allow(self):
        con = sqlite3.connect("UMRS.db")
        ind = self.t1.currentIndex()
        rw = ind.row()
        
        lid = self.t1.item(rw,0).text()
        name = self.t1.item(rw,1).text()
        mail = self.t1.item(rw,2).text()
        phone = self.t1.item(rw,3).text()
        add = self.t1.item(rw,4).text()
        addhar = self.t1.item(rw,5).text()
        pan = self.t1.item(rw,6).text()
        bank = self.t1.item(rw,7).text()
        account = self.t1.item(rw,8).text()
        ifsc = self.t1.item(rw,9).text()
        amt = self.t1.item(rw,10).text()
        dt = self.t1.item(rw,12).text()
        # print(phone)
        if rw == -1:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Warning)
            msg.setText("Select any request")
            msg.setWindowTitle("Warning")
            msg.show()
            msg.exec_()    
        #       pass
        else:
            cur = con.cursor()
            q1 = "delete from Loan_Request where PhoneNo = ?"
            cur.execute(q1,(phone,))
            self.t1.removeRow(rw)
            
            cur2 = con.cursor()
            q2 = "insert into approveRequest values (?,?,?,?,?,?,?,?,?,?,?,?)"
            cur2.execute(q2,(lid,name,mail,phone,add,addhar,pan,bank,account,ifsc,amt,dt))

            msg = QMessageBox()
            msg.setIcon(QMessageBox.Information)
            msg.setText("Loan Approved")
            msg.setWindowTitle("Approved")
            msg.show()
            msg.exec_()
            
        con.commit()

    def deny(self):
        ind = self.t1.currentIndex()
        rw = ind.row()
        self.t1.removeRow(rw)

        msg = QMessageBox()
        msg.setIcon(QMessageBox.Information)
        msg.setText("Request deny")
        msg.setWindowTitle("Loan")
        msg.show()
        msg.exec_()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
