from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
from PyQt5.QtWidgets import QMessageBox

class Ui_book(object):
    def setupUi(self, book):
        book.setObjectName("book")
        book.resize(800, 592)
        self.centralwidget = QtWidgets.QWidget(book)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.frame)
        self.frame_6 = QtWidgets.QFrame(self.centralwidget)
        self.frame_6.setMinimumSize(QtCore.QSize(400, 0))
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.edition = QtWidgets.QLineEdit(self.frame_6)
        self.edition.setMaximumSize(QtCore.QSize(16777215, 30))
        self.edition.setObjectName("edition")
        self.horizontalLayout.addWidget(self.edition)
        self.verticalLayout.addWidget(self.frame_6, 0, QtCore.Qt.AlignHCenter)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(400, 0))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.sub = QtWidgets.QComboBox(self.frame_2)
        self.sub.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setFamily("MoolBoran")
        font.setPointSize(16)
        self.sub.setFont(font)
        self.sub.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sub.setObjectName("sub")
        self.sub.addItem("")
        self.sub.setItemText(0, "")
        self.horizontalLayout_2.addWidget(self.sub)
        self.verticalLayout.addWidget(self.frame_2, 0, QtCore.Qt.AlignHCenter)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setMinimumSize(QtCore.QSize(400, 0))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.authorName = QtWidgets.QLineEdit(self.frame_3)
        self.authorName.setMaximumSize(QtCore.QSize(16777215, 30))
        self.authorName.setObjectName("authorName")
        self.horizontalLayout_3.addWidget(self.authorName)
        self.verticalLayout.addWidget(self.frame_3, 0, QtCore.Qt.AlignHCenter)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setMinimumSize(QtCore.QSize(400, 0))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.bookName = QtWidgets.QLineEdit(self.frame_4)
        self.bookName.setMaximumSize(QtCore.QSize(16777215, 30))
        self.bookName.setObjectName("bookName")
        self.horizontalLayout_4.addWidget(self.bookName)
        self.verticalLayout.addWidget(self.frame_4, 0, QtCore.Qt.AlignHCenter)
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setMinimumSize(QtCore.QSize(400, 0))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.pub = QtWidgets.QLineEdit(self.frame_5)
        self.pub.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pub.setObjectName("pub")
        self.horizontalLayout_5.addWidget(self.pub)
        self.verticalLayout.addWidget(self.frame_5, 0, QtCore.Qt.AlignHCenter)
        self.frame_7 = QtWidgets.QFrame(self.centralwidget)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.add = QtWidgets.QPushButton(self.frame_7)
        self.add.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add.setObjectName("add")
        self.horizontalLayout_7.addWidget(self.add)
        self.verticalLayout.addWidget(self.frame_7, 0, QtCore.Qt.AlignHCenter)
        book.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(book)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        book.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(book)
        self.statusbar.setObjectName("statusbar")
        book.setStatusBar(self.statusbar)

        self.retranslateUi(book)
        QtCore.QMetaObject.connectSlotsByName(book)

        # self.add.setEnabled(False)
        self.add.clicked.connect(self.addbook)
        self.subName()
        self.add.clicked.connect(book.close)

    def retranslateUi(self, book):
        _translate = QtCore.QCoreApplication.translate
        book.setWindowTitle(_translate("book", "Add Book"))
        self.label.setText(_translate("book", "Add Book"))
        self.label_5.setText(_translate("book", "Edition"))
        self.label_9.setText(_translate("book", "Subject Name"))
        self.label_3.setText(_translate("book", "Author name"))
        self.label_2.setText(_translate("book", "Book name"))
        self.label_4.setText(_translate("book", "Publisher"))
        self.add.setText(_translate("book", "Add"))

    def addbook(self):
        auth = self.authorName.text().lstrip().rstrip()
        bn = self.bookName.text().lstrip().rstrip()
        pub = self.pub.text().lstrip().rstrip()
        ed = self.edition.text().lstrip().rstrip()
        s = self.sub.currentText()
        # print(s)
        
        con = sqlite3.connect("projectDB.db")
        cur = con.cursor()
        q = "insert into addBooks values (?,?,?,?,?)"
        cur.execute(q,(s,auth,bn,pub,ed))
        
        cur1 = con.cursor()
        q1 = "insert into bookStock values (?,?,?,?,?,?)"
        cur1.execute(q1,(s,bn,auth,pub,ed,0))
        con.commit()

        msg = QMessageBox()
        msg.setIcon(QMessageBox.Information)
        msg.setText("1 book is added")
        msg.setWindowTitle("add book")
        msg.show()
        msg.exec_()

    def subName(self):
        con = sqlite3.connect("projectDB.db")
        cur = con.cursor()
        q1 = "select * from addSubject"
        cur.execute(q1)
        c = cur.fetchall()
        for i in c:
            self.sub.addItem(i[0])

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    book = QtWidgets.QMainWindow()
    ui = Ui_book()
    ui.setupUi(book)
    book.show()
    sys.exit(app.exec_())
