# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addSubject.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
from PyQt5.QtWidgets import QMessageBox
from subjectEdit import *

class Ui_subject(object):
    def setupUi(self, subject):
        subject.setObjectName("subject")
        subject.resize(797, 596)
        self.centralwidget = QtWidgets.QWidget(subject)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.subName = QtWidgets.QLineEdit(self.frame_2)
        self.subName.setMinimumSize(QtCore.QSize(200, 0))
        self.subName.setMaximumSize(QtCore.QSize(200, 30))
        self.subName.setObjectName("subName")
        self.horizontalLayout.addWidget(self.subName)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.add = QtWidgets.QPushButton(self.frame_3)
        self.add.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add.setObjectName("add")
        self.verticalLayout_3.addWidget(self.add)
        self.horizontalLayout.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.frame_2, 0, QtCore.Qt.AlignHCenter)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_4.setMaximumSize(QtCore.QSize(150, 300))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.subTable = QtWidgets.QTableWidget(self.frame_4)
        self.subTable.setObjectName("subTable")
        self.subTable.setColumnCount(1)
        self.subTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.subTable.setHorizontalHeaderItem(0, item)
        self.verticalLayout_5.addWidget(self.subTable)
        self.edit = QtWidgets.QPushButton(self.frame_4)
        self.edit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.edit.setObjectName("edit")
        self.verticalLayout_5.addWidget(self.edit)
        self.remove = QtWidgets.QPushButton(self.frame_4)
        self.remove.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.remove.setObjectName("remove")
        self.verticalLayout_5.addWidget(self.remove)
        self.verticalLayout.addWidget(self.frame_4, 0, QtCore.Qt.AlignHCenter)
        subject.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(subject)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 797, 21))
        self.menubar.setObjectName("menubar")
        subject.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(subject)
        self.statusbar.setObjectName("statusbar")
        subject.setStatusBar(self.statusbar)

        self.retranslateUi(subject)
        QtCore.QMetaObject.connectSlotsByName(subject)

        self.add.clicked.connect(self.addSub)
        self.remove.clicked.connect(self.removeSub)
        self.edit.clicked.connect(self.editSub)
        # self.edit.clicked.connect(subject.close)
        self.showSub()

    def retranslateUi(self, subject):
        _translate = QtCore.QCoreApplication.translate
        subject.setWindowTitle(_translate("subject", "Add Subject"))
        self.label.setText(_translate("subject", "Add Subject"))
        self.label_2.setText(_translate("subject", "Subject Name"))
        self.add.setText(_translate("subject", "Add"))
        item = self.subTable.horizontalHeaderItem(0)
        item.setText(_translate("subject", "Subject Name"))
        self.edit.setText(_translate("subject", "Edit"))
        self.remove.setText(_translate("subject", "Remove"))

    def addSub(self):
        s = self.subName.text()
        con = sqlite3.connect("projectDB.db")
        cur = con.cursor()
        
        try: 
            if s == "":
                msg = QMessageBox()
                msg.setIcon(QMessageBox.Critical)
                msg.setText("Fields cann't be empty")
                msg.setWindowTitle("Warning")
                msg.show()
                msg.exec_()
            else:
                q = "insert into addSubject values (?)"
                cur.execute(q,(s,))
                con.commit()
                msg = QMessageBox()
                msg.setIcon(QMessageBox.Information)
                msg.setText("Subject inserted")
                msg.setWindowTitle("Insert")
                msg.show()
                msg.exec_()
                self.showSub()
        
        except sqlite3.IntegrityError:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Warning)
            msg.setText("Subject name already exists")
            msg.setWindowTitle("Warning")
            msg.show()
            msg.exec_()

    def showSub(self):
        con = sqlite3.connect("projectDB.db")
        cur = con.cursor()
        q =  "Select * from addSubject"
        cur.execute(q)
        res = cur.fetchall()
        self.subTable.setRowCount(0)
        for i in res:
            rc = self.subTable.rowCount()
            self.subTable.insertRow(rc)
            self.subTable.setItem(rc,0,QtWidgets.QTableWidgetItem(i[0]))
    
    def removeSub(self):
        # Delete from the table
        del_i = self.subTable.currentIndex()
        rw = del_i.row()
        self.subTable.removeRow(rw)
        
        # connect to the database
        con = sqlite3.connect("projectDB.db")
        cur = con.cursor()
        cur1 = con.cursor()
        
        # Select the particular row
        q = "select * from addSubject limit ?,1"
        cur.execute(q,(rw,))
        res = cur.fetchall()
        s = res[0]

        # Delete from DB
        if rw==-1:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Warning)
            msg.setText("Select any row")
            msg.setWindowTitle("Warning")
            msg.show()
            msg.exec_()
        else:
            nq = "delete from addSubject where SubjectName=?"
            cur1.execute(nq,s)
            con.commit()
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Information)
            msg.setText("One row is deleted")
            msg.setWindowTitle("Deleted")
            msg.show()
            msg.exec_()
            self.subName.setText(" ")

    def editSub(self):
        # s = self.courseName.text()
        i = self.subTable.currentIndex()
        rw = i.row()
        
        # connect to the database
        con = sqlite3.connect("projectDB.db")
        cur = con.cursor()
        
        # Select the particular row
        q = "select * from addSubject limit ?,1"
        cur.execute(q,(rw,))
        res = cur.fetchall()
        sName = res[0][0]
        
        # TRANSFER VALUE TO THE NEXT PAGE
        if rw == -1:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Warning)
            msg.setText("Select any row")
            msg.setWindowTitle("Warning")
            msg.show()
            msg.exec_()
        else:
            self.editSub = QtWidgets.QMainWindow()
            self.ui = Ui_editSub(sName)
            self.ui.setupUi(self.editSub)
            self.editSub.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    subject = QtWidgets.QMainWindow()
    ui = Ui_subject()
    ui.setupUi(subject)
    subject.show()
    sys.exit(app.exec_())
