# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'departmentPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
from PyQt5.QtWidgets import QMessageBox
from departmentEdit import *

class Ui_department(object):
    def setupUi(self, department):
        department.setObjectName("department")
        department.resize(800, 576)
        self.centralwidget = QtWidgets.QWidget(department)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.deptName = QtWidgets.QLineEdit(self.frame_2)
        self.deptName.setObjectName("deptName")
        self.horizontalLayout.addWidget(self.deptName)
        self.verticalLayout.addWidget(self.frame_2, 0, QtCore.Qt.AlignHCenter)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.add = QtWidgets.QPushButton(self.frame_3)
        self.add.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add.setObjectName("add")
        self.horizontalLayout_2.addWidget(self.add)
        self.verticalLayout.addWidget(self.frame_3, 0, QtCore.Qt.AlignHCenter)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_4.setMaximumSize(QtCore.QSize(120, 250))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.deptTable = QtWidgets.QTableWidget(self.frame_4)
        self.deptTable.setObjectName("deptTable")
        self.deptTable.setColumnCount(1)
        self.deptTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.deptTable.setHorizontalHeaderItem(0, item)
        self.verticalLayout_3.addWidget(self.deptTable)
        self.edit = QtWidgets.QPushButton(self.frame_4)
        self.edit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.edit.setObjectName("edit")
        self.verticalLayout_3.addWidget(self.edit)
        self.remove = QtWidgets.QPushButton(self.frame_4)
        self.remove.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.remove.setObjectName("remove")
        self.verticalLayout_3.addWidget(self.remove)
        self.verticalLayout.addWidget(self.frame_4, 0, QtCore.Qt.AlignHCenter)
        department.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(department)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        department.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(department)
        self.statusbar.setObjectName("statusbar")
        department.setStatusBar(self.statusbar)

        self.retranslateUi(department)
        QtCore.QMetaObject.connectSlotsByName(department)

        self.add.clicked.connect(self.addCourse)
        self.remove.clicked.connect(self.removeCourse)
        self.edit.clicked.connect(self.editCourse)
        self.edit.clicked.connect(department.close)
        self.showCourse()

    def retranslateUi(self, department):
        _translate = QtCore.QCoreApplication.translate
        department.setWindowTitle(_translate("department", "Add department"))
        self.label.setText(_translate("department", "Department"))
        self.label_2.setText(_translate("department", "Department Name"))
        self.add.setText(_translate("department", "Add"))
        item = self.deptTable.horizontalHeaderItem(0)
        item.setText(_translate("department", "Department"))
        self.edit.setText(_translate("department", "Edit"))
        self.remove.setText(_translate("department", "Remove"))

    def addCourse(self):
        d = self.deptName.text()
        con = sqlite3.connect("projectDB.db")
        cur = con.cursor()
        try:
            if d == "":
                msg = QMessageBox()
                msg.setIcon(QMessageBox.Critical)
                msg.setText("Fields cann't be empty")
                msg.setWindowTitle("Warning")
                msg.show()
                msg.exec_()
            else:
                q = "insert into department values (?)"
                cur.execute(q,(d,))
                con.commit()
                msg = QMessageBox()
                msg.setIcon(QMessageBox.Information)
                msg.setText("Course inserted")
                msg.setWindowTitle("Insert")
                msg.show()
                msg.exec_()
                self.showCourse()
        except sqlite3.IntegrityError:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Warning)
            msg.setText("Department name already exists")
            msg.setWindowTitle("Warning")
            msg.show()
            msg.exec_()


    def showCourse(self):
        con = sqlite3.connect("projectDB.db")
        cur = con.cursor()
        q =  "Select * from department"
        cur.execute(q)
        res = cur.fetchall()
        self.deptTable.setRowCount(0)
        for i in res:
            rc = self.deptTable.rowCount()
            self.deptTable.insertRow(rc)
            self.deptTable.setItem(rc,0,QtWidgets.QTableWidgetItem(i[0]))
    
    def removeCourse(self):
        # Delete from the table
        del_i = self.deptTable.currentIndex()
        rw = del_i.row()
        self.deptTable.removeRow(rw)
        
        # connect to the database
        con = sqlite3.connect("projectDB.db")
        cur = con.cursor()
        cur1 = con.cursor()
        
        # Select the particular row
        q = "select * from department limit ?,1"
        cur.execute(q,(rw,))
        res = cur.fetchall()
        d = res[0]

        # Delete from DB
        if rw==-1:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Warning)
            msg.setText("Select any row")
            msg.setWindowTitle("Warning")
            msg.show()
            msg.exec_()
        else:
            nq = "delete from department where DepartmentName=?"
            cur1.execute(nq,d)
            con.commit()
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Information)
            msg.setText("One row is deleted")
            msg.setWindowTitle("Warning")
            msg.show()
            msg.exec_()
            self.deptName.setText(" ")

    def editCourse(self):
        # c = self.courseName.text()
        i = self.deptTable.currentIndex()
        rw = i.row()
        
        # connect to the database
        con = sqlite3.connect("projectDB.db")
        cur = con.cursor()
        
        # Select the particular row
        q = "select * from department limit ?,1"
        cur.execute(q,(rw,))
        res = cur.fetchall()
        dName = res[0][0]
        
        # TRANSFER VALUE TO THE NEXT PAGE
        if rw == -1:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Warning)
            msg.setText("Select any row")
            msg.setWindowTitle("Warning")
            msg.show()
            msg.exec_()
        else:
            # self.courseName.setText(r)
            self.deptEdit = QtWidgets.QMainWindow()
            self.ui = Ui_deptEdit(dName)
            self.ui.setupUi(self.deptEdit)
            self.deptEdit.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    department = QtWidgets.QMainWindow()
    ui = Ui_department()
    ui.setupUi(department)
    department.show()
    sys.exit(app.exec_())
