# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'departmentEdit.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
from PyQt5.QtWidgets import QMessageBox

class Ui_deptEdit(object):
    def __init__(self,d):
        self.dName=d
    def setupUi(self, deptEdit):
        deptEdit.setObjectName("deptEdit")
        deptEdit.resize(800, 557)
        self.centralwidget = QtWidgets.QWidget(deptEdit)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.frame, 0, QtCore.Qt.AlignHCenter)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame_4)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.deptName = QtWidgets.QLineEdit(self.frame_2)
        self.deptName.setObjectName("deptName")
        self.horizontalLayout.addWidget(self.deptName)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame_4)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.update = QtWidgets.QPushButton(self.frame_3)
        self.update.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.update.setObjectName("update")
        self.verticalLayout_4.addWidget(self.update)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.frame_4, 0, QtCore.Qt.AlignHCenter)
        deptEdit.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(deptEdit)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        deptEdit.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(deptEdit)
        self.statusbar.setObjectName("statusbar")
        deptEdit.setStatusBar(self.statusbar)

        self.retranslateUi(deptEdit)
        QtCore.QMetaObject.connectSlotsByName(deptEdit)

        self.deptName.setText(self.dName)
        self.update.clicked.connect(self.deptUP)
        self.update.clicked.connect(deptEdit.close)

    def retranslateUi(self, deptEdit):
        _translate = QtCore.QCoreApplication.translate
        deptEdit.setWindowTitle(_translate("deptEdit", "Department Edit"))
        self.label.setText(_translate("deptEdit", "Department Edit"))
        self.label_2.setText(_translate("deptEdit", "New Department Name"))
        self.update.setText(_translate("deptEdit", "Update"))

    def deptUP(self):
        d = self.deptName.text()
        if d=="":
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("Fields cann't be empty")
            msg.setWindowTitle("Error")
            msg.show()
            msg.exec_()
        else:
            con = sqlite3.connect("projectDB.db")
            cur = con.cursor()
            up = "update department set DepartmentName = ? where DepartmentName= ?"
            cur.execute(up,(d,self.dName))
            con.commit()
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Information)
            msg.setText("One row updated")
            msg.setWindowTitle("Ok")
            msg.show()
            msg.exec_()
            
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    deptEdit = QtWidgets.QMainWindow()
    ui = Ui_deptEdit()
    ui.setupUi(deptEdit)
    deptEdit.show()
    sys.exit(app.exec_())
