# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'finePage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets 
from datetime import date
import sqlite3
from PyQt5.QtWidgets import QMessageBox

class Ui_finePage(object):
    def __init__(self,sid,bid,fine,sn,bn,ed,an,duedate):
        self.s = sid
        self.b = bid
        self.f = fine
        self.sn = sn
        self.bn = bn
        self.ed = ed
        self.an = an
        self.dd = duedate

    def setupUi(self, finePage):
        finePage.setObjectName("finePage")
        finePage.resize(800, 600)
        finePage.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(finePage)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.sid = QtWidgets.QLabel(self.frame_2)
        self.sid.setMinimumSize(QtCore.QSize(200, 0))
        self.sid.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        self.sid.setFont(font)
        self.sid.setObjectName("sid")
        self.horizontalLayout.addWidget(self.sid)
        self.verticalLayout.addWidget(self.frame_2, 0, QtCore.Qt.AlignHCenter)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setMinimumSize(QtCore.QSize(110, 0))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.bid = QtWidgets.QLabel(self.frame_3)
        self.bid.setMinimumSize(QtCore.QSize(200, 0))
        self.bid.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        self.bid.setFont(font)
        self.bid.setObjectName("bid")
        self.horizontalLayout_2.addWidget(self.bid)
        self.verticalLayout.addWidget(self.frame_3, 0, QtCore.Qt.AlignHCenter)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        self.label_5.setMinimumSize(QtCore.QSize(110, 0))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.amt = QtWidgets.QLabel(self.frame_4)
        self.amt.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        self.amt.setFont(font)
        self.amt.setObjectName("amt")
        self.horizontalLayout_3.addWidget(self.amt)
        self.verticalLayout.addWidget(self.frame_4, 0, QtCore.Qt.AlignHCenter)
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.payFine = QtWidgets.QPushButton(self.frame_5)
        self.payFine.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.payFine.setObjectName("payFine")
        self.horizontalLayout_4.addWidget(self.payFine)
        self.verticalLayout.addWidget(self.frame_5, 0, QtCore.Qt.AlignHCenter)
        finePage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(finePage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        finePage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(finePage)
        self.statusbar.setObjectName("statusbar")
        finePage.setStatusBar(self.statusbar)

        self.retranslateUi(finePage)
        QtCore.QMetaObject.connectSlotsByName(finePage)

        self.sid.setText(str(self.s))
        self.bid.setText(self.b)
        self.amt.setText(str(self.f))
        self.payFine.clicked.connect(self.fine)
        self.payFine.clicked.connect(finePage.close)

    def retranslateUi(self, finePage):
        _translate = QtCore.QCoreApplication.translate
        finePage.setWindowTitle(_translate("finePage", "Fine Page"))
        self.label.setText(_translate("finePage", "Fine"))
        self.label_3.setText(_translate("finePage", "SID"))
        self.sid.setText(_translate("finePage", "SID"))
        self.label_4.setText(_translate("finePage", "AccessionNo"))
        self.bid.setText(_translate("finePage", "Book ID"))
        self.label_5.setText(_translate("finePage", "Amount"))
        self.amt.setText(_translate("finePage", "Amount"))
        self.payFine.setText(_translate("finePage", "Pay and Return"))

    def fine(self):
        today = date.today()
        con = sqlite3.connect("projectDB.db")

        cur = con.cursor()
        q = "select FineID from fine order by FineID desc limit 1"
        cur.execute(q)
        res = cur.fetchall()
        # print(res)
        l = []
        if res == l :
            fine = "F101"
        else:
            l = res[0][0]
            no = str(int(l[1:len(l)])+1)
            fine = "F" + no
        # print(fine)

        cur = con.cursor()
        q1 = "update bookStock set Stock = (Stock + 1) where SubjectName = ? and BookName = ? and Edition = ? and AuthorName = ?"
        cur.execute(q1,(self.sn,self.bn,self.ed,self.an))

        if today > self.dd:
            cur = con.cursor()
            q = "update issueBook set ReturnDate = ?, FineID = ? where BookID = ? and SID = ? and ReturnDate = ?"
            cur.execute(q,(today,fine,self.b,int(self.s),"NULL"))

        cur = con.cursor()
        q = "insert into fine values (?,?,?,?,?)"
        cur.execute(q,(fine,self.b,int(self.s),int(self.f),today))

        con.commit()

        msg = QMessageBox()
        msg.setIcon(QMessageBox.Information)
        msg.setText("Book returned")
        msg.setWindowTitle("Return Book")
        msg.show()
        msg.exec_()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    finePage = QtWidgets.QMainWindow()
    ui = Ui_finePage()
    ui.setupUi(finePage)
    finePage.show()
    sys.exit(app.exec_())
