# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'subjectEdit.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
from PyQt5.QtWidgets import QMessageBox

class Ui_editSub(object):

    def __init__(self,s):
        self.sName=s
    def setupUi(self, editSub):
        editSub.setObjectName("editSub")
        editSub.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(editSub)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.subName = QtWidgets.QLineEdit(self.frame_2)
        self.subName.setMinimumSize(QtCore.QSize(213, 0))
        self.subName.setMaximumSize(QtCore.QSize(16777215, 30))
        self.subName.setObjectName("subName")
        self.horizontalLayout.addWidget(self.subName)
        self.update = QtWidgets.QPushButton(self.frame_2)
        self.update.setMaximumSize(QtCore.QSize(16777215, 30))
        self.update.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.update.setObjectName("update")
        self.horizontalLayout.addWidget(self.update)
        self.verticalLayout.addWidget(self.frame_2, 0, QtCore.Qt.AlignHCenter)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout.addWidget(self.frame_3)
        editSub.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(editSub)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        editSub.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(editSub)
        self.statusbar.setObjectName("statusbar")
        editSub.setStatusBar(self.statusbar)

        self.retranslateUi(editSub)
        QtCore.QMetaObject.connectSlotsByName(editSub)

        self.subName.setText(self.sName)
        self.update.clicked.connect(self.subUP)
        self.update.clicked.connect(editSub.close)

    def retranslateUi(self, editSub):
        _translate = QtCore.QCoreApplication.translate
        editSub.setWindowTitle(_translate("editSub", "Subject Edit"))
        self.label.setText(_translate("editSub", "Subject Edit"))
        self.label_2.setText(_translate("editSub", "New Subject Name"))
        self.update.setText(_translate("editSub", "Update"))

    def subUP(self):
        s = self.subName.text()
        if s=="":
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("Fields cann't be empty")
            msg.setWindowTitle("Error")
            msg.show()
            msg.exec_()
        else:
            con = sqlite3.connect("projectDB.db")
            cur = con.cursor()
            up = "update addSubject set SubjectName = ? where SubjectName= ?"
            cur.execute(up,(s,self.sName))
            con.commit()
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Information)
            msg.setText("One row updated")
            msg.setWindowTitle("Ok")
            msg.show()
            msg.exec_()
            
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    editSub = QtWidgets.QMainWindow()
    ui = Ui_editSub()
    ui.setupUi(editSub)
    editSub.show()
    sys.exit(app.exec_())
